### ISSUE TITLE
U

### ISSUE THREAD

**Issue by vader355** [vader355/kone-n-#4]
I believe this specific domain(s) is to be moved from the hosts file as it no longer is active for Adult material

## Delete this
```
dead.example.com
```

## Keep this
```
alive.example.com
```

## Screenshots

<details><Summary>Screenshot</summary>

</details>

### All Submissions:
- [ ] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Merge Requests (MR)](../merge_requests) or [Issues](../issues) for the same update/change?
- [ ] Added ScreenDump for prove of False Positive

### Todo
- [ ] Removed this from [Source file](submit_here/hosts.txt)?
- [ ] Removed from the RPZ zone [adult.mypdns.cloud](https://www.mypdns.org/wiki/RpzList#adult.mypdns.cloud) (@spirillen)
